### ISSUE TITLE
how differs from lsd?

### ISSUE THREAD

**Issue by goyalyashpal** [arp242/elles#1]
hi! congo on reaching top on yc/hn show.
i would have shared the link to page, but i dot know how to get it

> It differs from [eza](https://github.com/eza-community/eza) or [lsd](https://github.com/lsd-rs/lsd) in that it has a slightly different feature set, and makes some different choices about various aspects.

i have recently settled on lsd, and that seem to be fairly well rounded package, and fairly open to feature requests. did u try reaching them?

* > This is the main reason I started working on this. `ls -l` is often too much info.

   true, `lsd` has `--blocks{=| }...` option for that, so like `lsd --blocks date,size,name`, but yeah, having a different preset of blocks at disposal would be nice too 😇 

    https://github.com/lsd-rs/lsd/issues/96

* `lsd -l --header` is suuuuuper awesome too, i wish i had that soooo much when i was starting out with gnu utils/bash

* > "human-readable" file sizes by default

    same as `lsd`. also, which base? `10^{3n}` SI (K kilo, ...) or 2^{10n} binary (Ki kibi, ...)? 

    the `ls` seems to be using _worst_ of both worlds: uses `K` but means `Ki`

several things are intereating here:

* > `-g` and `-o` for `-l` without group or owner

    yeah, in an env where `lsd` was not available, i defaulted to using `ls -go` to save space and clutter lol

* > Anyway, use `-l` twice for more details:

    this feels similar to `eza`'s `-aa` for (almost-)all vs all

* > `-m` for CSV-y "Stream output format"

    how about using min 2 spaces as column separator by default? it makes parsing of output a breeze as `ssv`

* > `-c` uses create ("birth") time, rather than ctime  (which is usually identical to mtime, and is rarely useful for display or sorting).

    yeah, this is pain to understand and get the wanted output i guess on lsd too.

* > `-k` to set the blocksize to 1024 is not implemented as POSIX blocksize semantics are stupid.
   > 
   > `-s` uses the filesystem's block size rather than 512 or 1024 bytes. POSIX blocksize semantics are stupid. 

    oh yeah, yet another thing i never understood.

**Comment by ccoVeille** [comment]
Good questions @goyalyashpal 

I'm also `lsd` and `eza` user.

I like what  `elles` provides.

I agree with @arp242 status about lsd and eza.

But, I agree with @goyalyashpal, maybe opening issues on these repositories to try to address the issues @arp242 reported.

But, I'm following this project anyway.

**Comment by arp242** [comment]
I don't know Rust, so I can't contribute to lsd without learning Rust first. Learning Rust might not be a bad idea in general, but I also have other stuff to do. It was certainly faster to write this from scratch in a language I know.

I'm not going to open tons of issues for ideas that may or may not work well in the hopes that someday someone may or may not implement it. Here too it's faster and easier for everyone to just write something from scratch in a language I know.

lsd and elles can peacefully co-exist.

---

> > -m for CSV-y "Stream output format"
>
> how about using min 2 spaces as column separator by default? it makes parsing of output a breeze as ssv

What if a filename has two spaces? And shell scripts can't split on "two spaces" either (well, not POSIX sh AFAIK, although e.g. zsh can).

Does anyone use "ls -m"? I've never seen it and didn't even know it existed. In general "don't parse ls output" has been the advice for as long as I can remember.

There's the -json flag for all of this. Or use shell globs, find, etc.

> the ls seems to be using worst of both worlds: uses K but means Ki

This is what pretty much any ls implementation does on "-h". This is actually what almost *anything* does in the context of filesizes (and computers in general), where suffixes like "K", "M", etc. almost always mean base-1024.

The main exception are hard disk manufacturers and "but akshually" pedantics, both of whom have massively complicated the issue for no good reason at all.

> >  -k to set the blocksize to 1024 is not implemented as POSIX blocksize semantics are stupid.
> >
> > -s uses the filesystem's block size rather than 512 or 1024 bytes. POSIX blocksize semantics are stupid.
>
> oh yeah, yet another thing i never understood.

The original ls was a simple assembler program, and to print the "file size" it just printed the number of allocated filesystem blocks, which were always 512 bytes. That was a fine decision for a small research OS in 1971 with one filesystem and handful of users all in one office.

This convention stuck around, "for compatibility" or whatever. POSIX copied that because it's mostly a "document what implementations are doing"-type specification, rather than "prescribe what implementations should be doing".

BSD ls uses POSIX behaviour, but GNU ls ignores POSIX on this by default, but you can set "POSIXLY_CORRECT" to get POSIX behaviour.

**Comment by arp242** [comment]
Or let me put it this way:

I do almost everything from the CLI. Have done for the last 20 years or so. This works well for me.

I must run "ls" dozens of times every day.

It seems to me that it makes sense to spend some time to make sure it works exactly like I want. Of course I don't *need* to, but it would be nice. I have some ideas but I'm not yet 100% sure what will work well. The `-w` flag to set the maximum column width seems very useful for example and I added `-w60` in my default alias.

Will I like that? Maybe I need to do something else? I don't know until I've tried it for a while.

I went back and forth on adding those borders for a long time. `ls` doesn't have them so I wasn't used to it, but eventually I liked it, as it "guides" the eyes and makes it quicker to scan things. It took me a while of actually using it and playing around with different options to discover this.

You can't get this sort of thing by "sending feature requests".

And in the end: there's always something to do different. Not "better", just "different". People could have said "but `ls` already exists!" when they started working on exa or lsd. Just a quick look at the defaults show that `ls`, `lsd`, `eza`, and `elles` all make very different choices:

![cap-2024-06-14T19:30:28_border](https://github.com/arp242/elles/assets/1032692/d33c2cfa-067a-4624-8060-20c38442eaa3)

**Comment by goyalyashpal** [comment]
> This is actually what almost anything does in the context of filesizes (and computers in general), where suffixes like "K", "M", etc. almost always mean base-1024.
> \- @ arp242 at https://github.com/arp242/elles/issues/1#issuecomment-2168466859

well, at least on windows i can confirm thats not the case; the browser says smth different when downloading smth, `aria2c` said smth else, dont remember if doublecmd and win-exploroer tallied in their listing too.

**Comment by arp242** [comment]
Windows Explorer uses base-1024. Always has as far as I know. If you open file properties it shows you both the abbreviated "human" size and byte size.

I don't know about aria2c or doublecmd, I never heard of those. I'm sure there are *some* programs where "K" means "base 1000", but it's not the default for the vast majority of programs.

Regardless of what Windows or some random programs do, this is how all `/bin/ls` implementations with a `-h` flag have behaved for decades. As do `/bin/du`, `/bin/df`, etc. etc. GNU ls has a --si option to change this, but most don't even have that.
